<?php
 //IP DE LA PC SERVIDOR DE BASE DE DATOS
define("DB_HOST",'localhost');

//NOMBRE DE LA BASE DE DATOS
define("DB_NAME",'dbsistema');

//USUARIO DE LA BASE DE DATOS
define("DB_USERNAME",'root');
//CONTRASEÑA DE LA BASE DE DATOS
define("DB_PASSWORD",'');

//DEFINIMOS LA CODIFICACION DE CARACTERES
define("DB_ENCODE",'utf8');
//DEFINIMOS UNA CONSTANTE COMO NOMBRE DEL PROYECTO
define("PRO_NOMBRE",'SISTEMA DE VENTAS');
 ?>
